package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Channel generated by hbm2java
 */
public class Channel  implements java.io.Serializable {


     private Integer idChannel;
     private Integer code;
     private String name;

    public Channel() {
    }

    public Channel(Integer code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public Integer getIdChannel() {
        return this.idChannel;
    }
    
    public void setIdChannel(Integer idChannel) {
        this.idChannel = idChannel;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


