package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer idCountry;
     private String name;

    public Country() {
    }

    public Country(String name) {
       this.name = name;
    }
   
    public Integer getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Integer idCountry) {
        this.idCountry = idCountry;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


