package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Device generated by hbm2java
 */
public class Device  implements java.io.Serializable {


     private Integer idDevice;
     private int stbDeviceIdStbDevice;
     private String serialNumber;
     private String type;
     private String profile;

    public Device() {
    }

	
    public Device(int stbDeviceIdStbDevice) {
        this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
    }
    public Device(int stbDeviceIdStbDevice, String serialNumber, String type, String profile) {
       this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
       this.serialNumber = serialNumber;
       this.type = type;
       this.profile = profile;
    }
   
    public Integer getIdDevice() {
        return this.idDevice;
    }
    
    public void setIdDevice(Integer idDevice) {
        this.idDevice = idDevice;
    }
    public int getStbDeviceIdStbDevice() {
        return this.stbDeviceIdStbDevice;
    }
    
    public void setStbDeviceIdStbDevice(int stbDeviceIdStbDevice) {
        this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }




}


