package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer iddocument;
     private int nclStateMachineIdnclStateMachine;
     private String id;

    public Document() {
    }

	
    public Document(int nclStateMachineIdnclStateMachine) {
        this.nclStateMachineIdnclStateMachine = nclStateMachineIdnclStateMachine;
    }
    public Document(int nclStateMachineIdnclStateMachine, String id) {
       this.nclStateMachineIdnclStateMachine = nclStateMachineIdnclStateMachine;
       this.id = id;
    }
   
    public Integer getIddocument() {
        return this.iddocument;
    }
    
    public void setIddocument(Integer iddocument) {
        this.iddocument = iddocument;
    }
    public int getNclStateMachineIdnclStateMachine() {
        return this.nclStateMachineIdnclStateMachine;
    }
    
    public void setNclStateMachineIdnclStateMachine(int nclStateMachineIdnclStateMachine) {
        this.nclStateMachineIdnclStateMachine = nclStateMachineIdnclStateMachine;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }




}


