package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Head generated by hbm2java
 */
public class Head  implements java.io.Serializable {


     private Integer idHead;
     private int userIdUser;
     private int locationIdLocation;
     private int watchTvIdWatchTv;
     private int stbDeviceIdStbDevice;

    public Head() {
    }

    public Head(int userIdUser, int locationIdLocation, int watchTvIdWatchTv, int stbDeviceIdStbDevice) {
       this.userIdUser = userIdUser;
       this.locationIdLocation = locationIdLocation;
       this.watchTvIdWatchTv = watchTvIdWatchTv;
       this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
    }
   
    public Integer getIdHead() {
        return this.idHead;
    }
    
    public void setIdHead(Integer idHead) {
        this.idHead = idHead;
    }
    public int getUserIdUser() {
        return this.userIdUser;
    }
    
    public void setUserIdUser(int userIdUser) {
        this.userIdUser = userIdUser;
    }
    public int getLocationIdLocation() {
        return this.locationIdLocation;
    }
    
    public void setLocationIdLocation(int locationIdLocation) {
        this.locationIdLocation = locationIdLocation;
    }
    public int getWatchTvIdWatchTv() {
        return this.watchTvIdWatchTv;
    }
    
    public void setWatchTvIdWatchTv(int watchTvIdWatchTv) {
        this.watchTvIdWatchTv = watchTvIdWatchTv;
    }
    public int getStbDeviceIdStbDevice() {
        return this.stbDeviceIdStbDevice;
    }
    
    public void setStbDeviceIdStbDevice(int stbDeviceIdStbDevice) {
        this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
    }




}


