package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Information generated by hbm2java
 */
public class Information  implements java.io.Serializable {


     private Integer idInformation;
     private int resourceIdResource;
     private String name;
     private String value;

    public Information() {
    }

	
    public Information(int resourceIdResource) {
        this.resourceIdResource = resourceIdResource;
    }
    public Information(int resourceIdResource, String name, String value) {
       this.resourceIdResource = resourceIdResource;
       this.name = name;
       this.value = value;
    }
   
    public Integer getIdInformation() {
        return this.idInformation;
    }
    
    public void setIdInformation(Integer idInformation) {
        this.idInformation = idInformation;
    }
    public int getResourceIdResource() {
        return this.resourceIdResource;
    }
    
    public void setResourceIdResource(int resourceIdResource) {
        this.resourceIdResource = resourceIdResource;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


