package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Interface generated by hbm2java
 */
public class Interface  implements java.io.Serializable {


     private Integer idInterface;
     private int mediaIdMedia;
     private String id;
     private String status;

    public Interface() {
    }

	
    public Interface(int mediaIdMedia) {
        this.mediaIdMedia = mediaIdMedia;
    }
    public Interface(int mediaIdMedia, String id, String status) {
       this.mediaIdMedia = mediaIdMedia;
       this.id = id;
       this.status = status;
    }
   
    public Integer getIdInterface() {
        return this.idInterface;
    }
    
    public void setIdInterface(Integer idInterface) {
        this.idInterface = idInterface;
    }
    public int getMediaIdMedia() {
        return this.mediaIdMedia;
    }
    
    public void setMediaIdMedia(int mediaIdMedia) {
        this.mediaIdMedia = mediaIdMedia;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


