package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Iteraction generated by hbm2java
 */
public class Iteraction  implements java.io.Serializable {


     private Integer idIteraction;
     private int programIdProgram;
     private int volumeIdVolume;
     private int keyIdKey;
     private int watchTvIdWatchTv;
     private Date time;
     private String type;

    public Iteraction() {
    }

	
    public Iteraction(int programIdProgram, int volumeIdVolume, int keyIdKey, int watchTvIdWatchTv) {
        this.programIdProgram = programIdProgram;
        this.volumeIdVolume = volumeIdVolume;
        this.keyIdKey = keyIdKey;
        this.watchTvIdWatchTv = watchTvIdWatchTv;
    }
    public Iteraction(int programIdProgram, int volumeIdVolume, int keyIdKey, int watchTvIdWatchTv, Date time, String type) {
       this.programIdProgram = programIdProgram;
       this.volumeIdVolume = volumeIdVolume;
       this.keyIdKey = keyIdKey;
       this.watchTvIdWatchTv = watchTvIdWatchTv;
       this.time = time;
       this.type = type;
    }
   
    public Integer getIdIteraction() {
        return this.idIteraction;
    }
    
    public void setIdIteraction(Integer idIteraction) {
        this.idIteraction = idIteraction;
    }
    public int getProgramIdProgram() {
        return this.programIdProgram;
    }
    
    public void setProgramIdProgram(int programIdProgram) {
        this.programIdProgram = programIdProgram;
    }
    public int getVolumeIdVolume() {
        return this.volumeIdVolume;
    }
    
    public void setVolumeIdVolume(int volumeIdVolume) {
        this.volumeIdVolume = volumeIdVolume;
    }
    public int getKeyIdKey() {
        return this.keyIdKey;
    }
    
    public void setKeyIdKey(int keyIdKey) {
        this.keyIdKey = keyIdKey;
    }
    public int getWatchTvIdWatchTv() {
        return this.watchTvIdWatchTv;
    }
    
    public void setWatchTvIdWatchTv(int watchTvIdWatchTv) {
        this.watchTvIdWatchTv = watchTvIdWatchTv;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


