package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Key generated by hbm2java
 */
public class Key  implements java.io.Serializable {


     private Integer idKey;
     private String code;
     private String action;

    public Key() {
    }

    public Key(String code, String action) {
       this.code = code;
       this.action = action;
    }
   
    public Integer getIdKey() {
        return this.idKey;
    }
    
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


