package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer idLocation;
     private Integer zip;
     private Double latitude;
     private Double longitude;

    public Location() {
    }

    public Location(Integer zip, Double latitude, Double longitude) {
       this.zip = zip;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }
    public Integer getZip() {
        return this.zip;
    }
    
    public void setZip(Integer zip) {
        this.zip = zip;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }




}


