package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Meta generated by hbm2java
 */
public class Meta  implements java.io.Serializable {


     private Integer idMeta;
     private int programIdProgram;
     private String meta;

    public Meta() {
    }

	
    public Meta(int programIdProgram) {
        this.programIdProgram = programIdProgram;
    }
    public Meta(int programIdProgram, String meta) {
       this.programIdProgram = programIdProgram;
       this.meta = meta;
    }
   
    public Integer getIdMeta() {
        return this.idMeta;
    }
    
    public void setIdMeta(Integer idMeta) {
        this.idMeta = idMeta;
    }
    public int getProgramIdProgram() {
        return this.programIdProgram;
    }
    
    public void setProgramIdProgram(int programIdProgram) {
        this.programIdProgram = programIdProgram;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }




}


