package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Nclstatemachine generated by hbm2java
 */
public class Nclstatemachine  implements java.io.Serializable {


     private Integer idnclStateMachine;
     private int iteractionIdIteraction;

    public Nclstatemachine() {
    }

    public Nclstatemachine(int iteractionIdIteraction) {
       this.iteractionIdIteraction = iteractionIdIteraction;
    }
   
    public Integer getIdnclStateMachine() {
        return this.idnclStateMachine;
    }
    
    public void setIdnclStateMachine(Integer idnclStateMachine) {
        this.idnclStateMachine = idnclStateMachine;
    }
    public int getIteractionIdIteraction() {
        return this.iteractionIdIteraction;
    }
    
    public void setIteractionIdIteraction(int iteractionIdIteraction) {
        this.iteractionIdIteraction = iteractionIdIteraction;
    }




}


