package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Integer idProgram;
     private int channelIdChannel;
     private Integer age;
     private String genre;
     private Integer code;
     private String name;
     private String subGenre;

    public Program() {
    }

	
    public Program(int channelIdChannel) {
        this.channelIdChannel = channelIdChannel;
    }
    public Program(int channelIdChannel, Integer age, String genre, Integer code, String name, String subGenre) {
       this.channelIdChannel = channelIdChannel;
       this.age = age;
       this.genre = genre;
       this.code = code;
       this.name = name;
       this.subGenre = subGenre;
    }
   
    public Integer getIdProgram() {
        return this.idProgram;
    }
    
    public void setIdProgram(Integer idProgram) {
        this.idProgram = idProgram;
    }
    public int getChannelIdChannel() {
        return this.channelIdChannel;
    }
    
    public void setChannelIdChannel(int channelIdChannel) {
        this.channelIdChannel = channelIdChannel;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSubGenre() {
        return this.subGenre;
    }
    
    public void setSubGenre(String subGenre) {
        this.subGenre = subGenre;
    }




}


