package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Property generated by hbm2java
 */
public class Property  implements java.io.Serializable {


     private Integer idProperty;
     private int mediaIdMedia;
     private String name;
     private String value;

    public Property() {
    }

	
    public Property(int mediaIdMedia) {
        this.mediaIdMedia = mediaIdMedia;
    }
    public Property(int mediaIdMedia, String name, String value) {
       this.mediaIdMedia = mediaIdMedia;
       this.name = name;
       this.value = value;
    }
   
    public Integer getIdProperty() {
        return this.idProperty;
    }
    
    public void setIdProperty(Integer idProperty) {
        this.idProperty = idProperty;
    }
    public int getMediaIdMedia() {
        return this.mediaIdMedia;
    }
    
    public void setMediaIdMedia(int mediaIdMedia) {
        this.mediaIdMedia = mediaIdMedia;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


