package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {


     private Integer idResource;
     private Integer deviceIdDevice;
     private Integer stbDeviceIdStbDevice;
     private String type;

    public Resource() {
    }

    public Resource(Integer deviceIdDevice, Integer stbDeviceIdStbDevice, String type) {
       this.deviceIdDevice = deviceIdDevice;
       this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
       this.type = type;
    }
   
    public Integer getIdResource() {
        return this.idResource;
    }
    
    public void setIdResource(Integer idResource) {
        this.idResource = idResource;
    }
    public Integer getDeviceIdDevice() {
        return this.deviceIdDevice;
    }
    
    public void setDeviceIdDevice(Integer deviceIdDevice) {
        this.deviceIdDevice = deviceIdDevice;
    }
    public Integer getStbDeviceIdStbDevice() {
        return this.stbDeviceIdStbDevice;
    }
    
    public void setStbDeviceIdStbDevice(Integer stbDeviceIdStbDevice) {
        this.stbDeviceIdStbDevice = stbDeviceIdStbDevice;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


