package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Socialnetworkname generated by hbm2java
 */
public class Socialnetworkname  implements java.io.Serializable {


     private Integer idSocialNetWorkName;
     private String name;

    public Socialnetworkname() {
    }

    public Socialnetworkname(String name) {
       this.name = name;
    }
   
    public Integer getIdSocialNetWorkName() {
        return this.idSocialNetWorkName;
    }
    
    public void setIdSocialNetWorkName(Integer idSocialNetWorkName) {
        this.idSocialNetWorkName = idSocialNetWorkName;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


