package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * Socialnetwork generated by hbm2java
 */
public class Socialnetwork  implements java.io.Serializable {


     private Integer idSocialNetwork;
     private int userIdUser;
     private int socialNetWorkNameIdSocialNetWorkName;
     private String identification;

    public Socialnetwork() {
    }

	
    public Socialnetwork(int userIdUser, int socialNetWorkNameIdSocialNetWorkName) {
        this.userIdUser = userIdUser;
        this.socialNetWorkNameIdSocialNetWorkName = socialNetWorkNameIdSocialNetWorkName;
    }
    public Socialnetwork(int userIdUser, int socialNetWorkNameIdSocialNetWorkName, String identification) {
       this.userIdUser = userIdUser;
       this.socialNetWorkNameIdSocialNetWorkName = socialNetWorkNameIdSocialNetWorkName;
       this.identification = identification;
    }
   
    public Integer getIdSocialNetwork() {
        return this.idSocialNetwork;
    }
    
    public void setIdSocialNetwork(Integer idSocialNetwork) {
        this.idSocialNetwork = idSocialNetwork;
    }
    public int getUserIdUser() {
        return this.userIdUser;
    }
    
    public void setUserIdUser(int userIdUser) {
        this.userIdUser = userIdUser;
    }
    public int getSocialNetWorkNameIdSocialNetWorkName() {
        return this.socialNetWorkNameIdSocialNetWorkName;
    }
    
    public void setSocialNetWorkNameIdSocialNetWorkName(int socialNetWorkNameIdSocialNetWorkName) {
        this.socialNetWorkNameIdSocialNetWorkName = socialNetWorkNameIdSocialNetWorkName;
    }
    public String getIdentification() {
        return this.identification;
    }
    
    public void setIdentification(String identification) {
        this.identification = identification;
    }




}


