package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA



/**
 * StbDevice generated by hbm2java
 */
public class StbDevice  implements java.io.Serializable {


     private Integer idStbDevice;
     private String profile;
     private String type;
     private String serialNumber;

    public StbDevice() {
    }

    public StbDevice(String profile, String type, String serialNumber) {
       this.profile = profile;
       this.type = type;
       this.serialNumber = serialNumber;
    }
   
    public Integer getIdStbDevice() {
        return this.idStbDevice;
    }
    
    public void setIdStbDevice(Integer idStbDevice) {
        this.idStbDevice = idStbDevice;
    }
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }




}


