package POJOTVDI;
// Generated 27/03/2010 09:17:04 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WatchTv generated by hbm2java
 */
public class WatchTv  implements java.io.Serializable {


     private Integer idWatchTv;
     private int countryIdCountry;
     private Date startDate;
     private Date endDate;
     private Boolean flagEtl;

    public WatchTv() {
    }

	
    public WatchTv(int countryIdCountry) {
        this.countryIdCountry = countryIdCountry;
    }
    public WatchTv(int countryIdCountry, Date startDate, Date endDate, Boolean flagEtl) {
       this.countryIdCountry = countryIdCountry;
       this.startDate = startDate;
       this.endDate = endDate;
       this.flagEtl = flagEtl;
    }
   
    public Integer getIdWatchTv() {
        return this.idWatchTv;
    }
    
    public void setIdWatchTv(Integer idWatchTv) {
        this.idWatchTv = idWatchTv;
    }
    public int getCountryIdCountry() {
        return this.countryIdCountry;
    }
    
    public void setCountryIdCountry(int countryIdCountry) {
        this.countryIdCountry = countryIdCountry;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Boolean getFlagEtl() {
        return this.flagEtl;
    }
    
    public void setFlagEtl(Boolean flagEtl) {
        this.flagEtl = flagEtl;
    }




}


