package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * DimTime generated by hbm2java
 */
public class DimTime  implements java.io.Serializable {


     private Integer idDimTime;
     private Integer hour12;
     private Integer hour24;
     private Integer minute;
     private Integer second;

    public DimTime() {
    }

    public DimTime(Integer hour12, Integer hour24, Integer minute, Integer second) {
       this.hour12 = hour12;
       this.hour24 = hour24;
       this.minute = minute;
       this.second = second;
    }
   
    public Integer getIdDimTime() {
        return this.idDimTime;
    }
    
    public void setIdDimTime(Integer idDimTime) {
        this.idDimTime = idDimTime;
    }
    public Integer getHour12() {
        return this.hour12;
    }
    
    public void setHour12(Integer hour12) {
        this.hour12 = hour12;
    }
    public Integer getHour24() {
        return this.hour24;
    }
    
    public void setHour24(Integer hour24) {
        this.hour24 = hour24;
    }
    public Integer getMinute() {
        return this.minute;
    }
    
    public void setMinute(Integer minute) {
        this.minute = minute;
    }
    public Integer getSecond() {
        return this.second;
    }
    
    public void setSecond(Integer second) {
        this.second = second;
    }




}


