package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimProgram generated by hbm2java
 */
public class IteractionHasDimProgram  implements java.io.Serializable {


     private IteractionHasDimProgramId id;

    public IteractionHasDimProgram() {
    }

    public IteractionHasDimProgram(IteractionHasDimProgramId id) {
       this.id = id;
    }
   
    public IteractionHasDimProgramId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimProgramId id) {
        this.id = id;
    }




}


