package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimProgramId generated by hbm2java
 */
public class IteractionHasDimProgramId  implements java.io.Serializable {


     private int iteractionIdIteraction;
     private int dimProgramIdDimProgram;

    public IteractionHasDimProgramId() {
    }

    public IteractionHasDimProgramId(int iteractionIdIteraction, int dimProgramIdDimProgram) {
       this.iteractionIdIteraction = iteractionIdIteraction;
       this.dimProgramIdDimProgram = dimProgramIdDimProgram;
    }
   
    public int getIteractionIdIteraction() {
        return this.iteractionIdIteraction;
    }
    
    public void setIteractionIdIteraction(int iteractionIdIteraction) {
        this.iteractionIdIteraction = iteractionIdIteraction;
    }
    public int getDimProgramIdDimProgram() {
        return this.dimProgramIdDimProgram;
    }
    
    public void setDimProgramIdDimProgram(int dimProgramIdDimProgram) {
        this.dimProgramIdDimProgram = dimProgramIdDimProgram;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IteractionHasDimProgramId) ) return false;
		 IteractionHasDimProgramId castOther = ( IteractionHasDimProgramId ) other; 
         
		 return (this.getIteractionIdIteraction()==castOther.getIteractionIdIteraction())
 && (this.getDimProgramIdDimProgram()==castOther.getDimProgramIdDimProgram());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIteractionIdIteraction();
         result = 37 * result + this.getDimProgramIdDimProgram();
         return result;
   }   


}


