package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimData generated by hbm2java
 */
public class IteractionHasDimData  implements java.io.Serializable {


     private IteractionHasDimDataId id;

    public IteractionHasDimData() {
    }

    public IteractionHasDimData(IteractionHasDimDataId id) {
       this.id = id;
    }
   
    public IteractionHasDimDataId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimDataId id) {
        this.id = id;
    }




}


