package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimMedia generated by hbm2java
 */
public class IteractionHasDimMedia  implements java.io.Serializable {


     private IteractionHasDimMediaId id;

    public IteractionHasDimMedia() {
    }

    public IteractionHasDimMedia(IteractionHasDimMediaId id) {
       this.id = id;
    }
   
    public IteractionHasDimMediaId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimMediaId id) {
        this.id = id;
    }




}


