package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * ResourceStorage generated by hbm2java
 */
public class ResourceStorage  implements java.io.Serializable {


     private Integer idResourceStorage;
     private int dimDeviceIdDimDevice;
     private String total;
     private String free;

    public ResourceStorage() {
    }

	
    public ResourceStorage(int dimDeviceIdDimDevice) {
        this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }
    public ResourceStorage(int dimDeviceIdDimDevice, String total, String free) {
       this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
       this.total = total;
       this.free = free;
    }
   
    public Integer getIdResourceStorage() {
        return this.idResourceStorage;
    }
    
    public void setIdResourceStorage(Integer idResourceStorage) {
        this.idResourceStorage = idResourceStorage;
    }
    public int getDimDeviceIdDimDevice() {
        return this.dimDeviceIdDimDevice;
    }
    
    public void setDimDeviceIdDimDevice(int dimDeviceIdDimDevice) {
        this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getFree() {
        return this.free;
    }
    
    public void setFree(String free) {
        this.free = free;
    }




}


