package POJODW;
// Generated 30/06/2010 16:19:25 by Hibernate Tools 3.2.1.GA



/**
 * ResourceCpu generated by hbm2java
 */
public class ResourceCpu  implements java.io.Serializable {


     private Integer idResourceCpu;
     private int dimDeviceIdDimDevice;
     private String model;
     private String clock;
     private String cores;
     private String arch;

    public ResourceCpu() {
    }

	
    public ResourceCpu(int dimDeviceIdDimDevice) {
        this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }
    public ResourceCpu(int dimDeviceIdDimDevice, String model, String clock, String cores, String arch) {
       this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
       this.model = model;
       this.clock = clock;
       this.cores = cores;
       this.arch = arch;
    }
   
    public Integer getIdResourceCpu() {
        return this.idResourceCpu;
    }
    
    public void setIdResourceCpu(Integer idResourceCpu) {
        this.idResourceCpu = idResourceCpu;
    }
    public int getDimDeviceIdDimDevice() {
        return this.dimDeviceIdDimDevice;
    }
    
    public void setDimDeviceIdDimDevice(int dimDeviceIdDimDevice) {
        this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getClock() {
        return this.clock;
    }
    
    public void setClock(String clock) {
        this.clock = clock;
    }
    public String getCores() {
        return this.cores;
    }
    
    public void setCores(String cores) {
        this.cores = cores;
    }
    public String getArch() {
        return this.arch;
    }
    
    public void setArch(String arch) {
        this.arch = arch;
    }




}


