package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA



/**
 * DimDevice generated by hbm2java
 */
public class DimDevice  implements java.io.Serializable {


     private Integer idDimDevice;
     private String serialNumber;
     private String type;
     private String profile;

    public DimDevice() {
    }

    public DimDevice(String serialNumber, String type, String profile) {
       this.serialNumber = serialNumber;
       this.type = type;
       this.profile = profile;
    }
   
    public Integer getIdDimDevice() {
        return this.idDimDevice;
    }
    
    public void setIdDimDevice(Integer idDimDevice) {
        this.idDimDevice = idDimDevice;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }




}


