package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DimData generated by hbm2java
 */
public class DimData  implements java.io.Serializable {


     private Integer idDimData;
     private Integer dia;
     private Integer mes;
     private Integer ano;
     private String diaSemana;
     private Integer semana;
     private Integer quinzena;
     private Integer trimestre;
     private Integer bimestre;
     private Integer semestre;
     private Boolean feriasEscolares;
     private String feriadoNacional;
     private Date datacompleta;

    public DimData() {
    }

    public DimData(Integer dia, Integer mes, Integer ano, String diaSemana, Integer semana, Integer quinzena, Integer trimestre, Integer bimestre, Integer semestre, Boolean feriasEscolares, String feriadoNacional, Date datacompleta) {
       this.dia = dia;
       this.mes = mes;
       this.ano = ano;
       this.diaSemana = diaSemana;
       this.semana = semana;
       this.quinzena = quinzena;
       this.trimestre = trimestre;
       this.bimestre = bimestre;
       this.semestre = semestre;
       this.feriasEscolares = feriasEscolares;
       this.feriadoNacional = feriadoNacional;
       this.datacompleta = datacompleta;
    }
   
    public Integer getIdDimData() {
        return this.idDimData;
    }
    
    public void setIdDimData(Integer idDimData) {
        this.idDimData = idDimData;
    }
    public Integer getDia() {
        return this.dia;
    }
    
    public void setDia(Integer dia) {
        this.dia = dia;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Integer getSemana() {
        return this.semana;
    }
    
    public void setSemana(Integer semana) {
        this.semana = semana;
    }
    public Integer getQuinzena() {
        return this.quinzena;
    }
    
    public void setQuinzena(Integer quinzena) {
        this.quinzena = quinzena;
    }
    public Integer getTrimestre() {
        return this.trimestre;
    }
    
    public void setTrimestre(Integer trimestre) {
        this.trimestre = trimestre;
    }
    public Integer getBimestre() {
        return this.bimestre;
    }
    
    public void setBimestre(Integer bimestre) {
        this.bimestre = bimestre;
    }
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }
    public Boolean getFeriasEscolares() {
        return this.feriasEscolares;
    }
    
    public void setFeriasEscolares(Boolean feriasEscolares) {
        this.feriasEscolares = feriasEscolares;
    }
    public String getFeriadoNacional() {
        return this.feriadoNacional;
    }
    
    public void setFeriadoNacional(String feriadoNacional) {
        this.feriadoNacional = feriadoNacional;
    }
    public Date getDatacompleta() {
        return this.datacompleta;
    }
    
    public void setDatacompleta(Date datacompleta) {
        this.datacompleta = datacompleta;
    }




}


