package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DimMedia generated by hbm2java
 */
public class DimMedia  implements java.io.Serializable {


     private Integer idDimMedia;
     private String document;
     private String media;
     private String status;
     private Date time;

    public DimMedia() {
    }

    public DimMedia(String document, String media, String status, Date time) {
       this.document = document;
       this.media = media;
       this.status = status;
       this.time = time;
    }
   
    public Integer getIdDimMedia() {
        return this.idDimMedia;
    }
    
    public void setIdDimMedia(Integer idDimMedia) {
        this.idDimMedia = idDimMedia;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getMedia() {
        return this.media;
    }
    
    public void setMedia(String media) {
        this.media = media;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


