package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA



/**
 * DimUserHasDimSocialnetworkId generated by hbm2java
 */
public class DimUserHasDimSocialnetworkId  implements java.io.Serializable {


     private int dimUserIdDimUser;
     private int dimSocialNetworkIdDimSocialNetwork;

    public DimUserHasDimSocialnetworkId() {
    }

    public DimUserHasDimSocialnetworkId(int dimUserIdDimUser, int dimSocialNetworkIdDimSocialNetwork) {
       this.dimUserIdDimUser = dimUserIdDimUser;
       this.dimSocialNetworkIdDimSocialNetwork = dimSocialNetworkIdDimSocialNetwork;
    }
   
    public int getDimUserIdDimUser() {
        return this.dimUserIdDimUser;
    }
    
    public void setDimUserIdDimUser(int dimUserIdDimUser) {
        this.dimUserIdDimUser = dimUserIdDimUser;
    }
    public int getDimSocialNetworkIdDimSocialNetwork() {
        return this.dimSocialNetworkIdDimSocialNetwork;
    }
    
    public void setDimSocialNetworkIdDimSocialNetwork(int dimSocialNetworkIdDimSocialNetwork) {
        this.dimSocialNetworkIdDimSocialNetwork = dimSocialNetworkIdDimSocialNetwork;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DimUserHasDimSocialnetworkId) ) return false;
		 DimUserHasDimSocialnetworkId castOther = ( DimUserHasDimSocialnetworkId ) other; 
         
		 return (this.getDimUserIdDimUser()==castOther.getDimUserIdDimUser())
 && (this.getDimSocialNetworkIdDimSocialNetwork()==castOther.getDimSocialNetworkIdDimSocialNetwork());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDimUserIdDimUser();
         result = 37 * result + this.getDimSocialNetworkIdDimSocialNetwork();
         return result;
   }   


}


