package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimUser generated by hbm2java
 */
public class IteractionHasDimUser  implements java.io.Serializable {


     private IteractionHasDimUserId id;

    public IteractionHasDimUser() {
    }

    public IteractionHasDimUser(IteractionHasDimUserId id) {
       this.id = id;
    }
   
    public IteractionHasDimUserId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimUserId id) {
        this.id = id;
    }




}


