package POJODW;
// Generated 19/04/2010 17:52:17 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimDevice generated by hbm2java
 */
public class IteractionHasDimDevice  implements java.io.Serializable {


     private IteractionHasDimDeviceId id;

    public IteractionHasDimDevice() {
    }

    public IteractionHasDimDevice(IteractionHasDimDeviceId id) {
       this.id = id;
    }
   
    public IteractionHasDimDeviceId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimDeviceId id) {
        this.id = id;
    }




}


