package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * DimUserHasDimSocialnetwork generated by hbm2java
 */
public class DimUserHasDimSocialnetwork  implements java.io.Serializable {


     private DimUserHasDimSocialnetworkId id;

    public DimUserHasDimSocialnetwork() {
    }

    public DimUserHasDimSocialnetwork(DimUserHasDimSocialnetworkId id) {
       this.id = id;
    }
   
    public DimUserHasDimSocialnetworkId getId() {
        return this.id;
    }
    
    public void setId(DimUserHasDimSocialnetworkId id) {
        this.id = id;
    }




}


