package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimLocation generated by hbm2java
 */
public class IteractionHasDimLocation  implements java.io.Serializable {


     private IteractionHasDimLocationId id;

    public IteractionHasDimLocation() {
    }

    public IteractionHasDimLocation(IteractionHasDimLocationId id) {
       this.id = id;
    }
   
    public IteractionHasDimLocationId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimLocationId id) {
        this.id = id;
    }




}


