package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimTime generated by hbm2java
 */
public class IteractionHasDimTime  implements java.io.Serializable {


     private IteractionHasDimTimeId id;

    public IteractionHasDimTime() {
    }

    public IteractionHasDimTime(IteractionHasDimTimeId id) {
       this.id = id;
    }
   
    public IteractionHasDimTimeId getId() {
        return this.id;
    }
    
    public void setId(IteractionHasDimTimeId id) {
        this.id = id;
    }




}


