package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimDeviceId generated by hbm2java
 */
public class IteractionHasDimDeviceId  implements java.io.Serializable {


     private int iteractionIdIteraction;
     private int dimDeviceIdDimDevice;

    public IteractionHasDimDeviceId() {
    }

    public IteractionHasDimDeviceId(int iteractionIdIteraction, int dimDeviceIdDimDevice) {
       this.iteractionIdIteraction = iteractionIdIteraction;
       this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }
   
    public int getIteractionIdIteraction() {
        return this.iteractionIdIteraction;
    }
    
    public void setIteractionIdIteraction(int iteractionIdIteraction) {
        this.iteractionIdIteraction = iteractionIdIteraction;
    }
    public int getDimDeviceIdDimDevice() {
        return this.dimDeviceIdDimDevice;
    }
    
    public void setDimDeviceIdDimDevice(int dimDeviceIdDimDevice) {
        this.dimDeviceIdDimDevice = dimDeviceIdDimDevice;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IteractionHasDimDeviceId) ) return false;
		 IteractionHasDimDeviceId castOther = ( IteractionHasDimDeviceId ) other; 
         
		 return (this.getIteractionIdIteraction()==castOther.getIteractionIdIteraction())
 && (this.getDimDeviceIdDimDevice()==castOther.getDimDeviceIdDimDevice());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIteractionIdIteraction();
         result = 37 * result + this.getDimDeviceIdDimDevice();
         return result;
   }   


}


