package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimLocationId generated by hbm2java
 */
public class IteractionHasDimLocationId  implements java.io.Serializable {


     private int iteractionIdIteraction;
     private int dimLocationIdDimLocation;

    public IteractionHasDimLocationId() {
    }

    public IteractionHasDimLocationId(int iteractionIdIteraction, int dimLocationIdDimLocation) {
       this.iteractionIdIteraction = iteractionIdIteraction;
       this.dimLocationIdDimLocation = dimLocationIdDimLocation;
    }
   
    public int getIteractionIdIteraction() {
        return this.iteractionIdIteraction;
    }
    
    public void setIteractionIdIteraction(int iteractionIdIteraction) {
        this.iteractionIdIteraction = iteractionIdIteraction;
    }
    public int getDimLocationIdDimLocation() {
        return this.dimLocationIdDimLocation;
    }
    
    public void setDimLocationIdDimLocation(int dimLocationIdDimLocation) {
        this.dimLocationIdDimLocation = dimLocationIdDimLocation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IteractionHasDimLocationId) ) return false;
		 IteractionHasDimLocationId castOther = ( IteractionHasDimLocationId ) other; 
         
		 return (this.getIteractionIdIteraction()==castOther.getIteractionIdIteraction())
 && (this.getDimLocationIdDimLocation()==castOther.getDimLocationIdDimLocation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIteractionIdIteraction();
         result = 37 * result + this.getDimLocationIdDimLocation();
         return result;
   }   


}


