package POJODW;
// Generated 19/04/2010 22:24:40 by Hibernate Tools 3.2.1.GA



/**
 * IteractionHasDimMediaId generated by hbm2java
 */
public class IteractionHasDimMediaId  implements java.io.Serializable {


     private int iteractionIdIteraction;
     private int dimMediaIdDimMedia;

    public IteractionHasDimMediaId() {
    }

    public IteractionHasDimMediaId(int iteractionIdIteraction, int dimMediaIdDimMedia) {
       this.iteractionIdIteraction = iteractionIdIteraction;
       this.dimMediaIdDimMedia = dimMediaIdDimMedia;
    }
   
    public int getIteractionIdIteraction() {
        return this.iteractionIdIteraction;
    }
    
    public void setIteractionIdIteraction(int iteractionIdIteraction) {
        this.iteractionIdIteraction = iteractionIdIteraction;
    }
    public int getDimMediaIdDimMedia() {
        return this.dimMediaIdDimMedia;
    }
    
    public void setDimMediaIdDimMedia(int dimMediaIdDimMedia) {
        this.dimMediaIdDimMedia = dimMediaIdDimMedia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IteractionHasDimMediaId) ) return false;
		 IteractionHasDimMediaId castOther = ( IteractionHasDimMediaId ) other; 
         
		 return (this.getIteractionIdIteraction()==castOther.getIteractionIdIteraction())
 && (this.getDimMediaIdDimMedia()==castOther.getDimMediaIdDimMedia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIteractionIdIteraction();
         result = 37 * result + this.getDimMediaIdDimMedia();
         return result;
   }   


}


